# Dockerfile-mongodb

# Utilizar imagen base oficial de MongoDB
FROM mongo

# Crear directorio para almacenar datos de MongoDB
VOLUME /data/db

# Exponer el puerto de MongoDB
EXPOSE 27017

#Preguntar a alfredo sino requiere las variables de entorno??